
backend:
  name: github
  repo: sudoshekhu/arghya-v1.0
  branch: main
  auth_scope: repo
  client_id: Ov23lizHpF1omXODfrkB
  client_secret: 6c67ac49adf5d0e1ad6d4845830026e8916d69fb
  base_url: https://decap-cms-oauth.netlify.app


media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

site_url: https://arghya.co.in
display_url: https://arghya.co.in

collections:
  - name: "home"
    label: "Home Page"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "content/home/hero.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }

